cherry-picked the commit from master to v2 in customizingyourgateway.md
grpc-ecosystem/grpc-gateway pull request #1374
Opened 2020-05-21 16:27 UTC by iamrajiv

#### References to other Issues or PRs
#1359

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
cherry-picked the commit from master to v2 in `customizingyourgateway.md`

#### Other comments

2020-05-21 16:40 UTC, johanbrandhorst requested changes

2020-05-21 16:40 UTC, johanbrandhorst commented on docs/_docs/customizingyourgateway.md
> +any `ServeMux` set up with the `WithProtoErrorHandler` option.
As you can see, these docs have actually changed between master and v2, so you're probably best of just going over this file separately.

2020-05-21 21:16 UTC, iamrajiv commented
@johanbrandhorst please review my last changes

2020-05-22 07:56 UTC, johanbrandhorst approved these changes

2020-05-22 07:57 UTC, merged

2020-05-22 07:57 UTC, johanbrandhorst commented
Thanks for your contribution!