Multiple repeated fields are allowed
grpc-ecosystem/grpc-gateway pull request #1921
Opened 2021-01-24 10:10 UTC by topherCantrell

The protobuffer comments have been corrected here:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto#L85-L86

The restriction was intended for the path string itself and not the
entire mask. There can be only one repeated field in a path string, and
when we get to it, the path string is done.

We found ourselves using multiple repeated fields in a message.

This fixes:

https://github.com/grpc-ecosystem/grpc-gateway/issues/1766

2021-01-24 10:17 UTC, topherCantrell commented
@googlebot I signed it!

2021-01-24 15:57 UTC, nashikb commented
Thanks @topherCantrell! This was still on my list, but hadn't yet made it to the top.

2021-01-24 15:58 UTC, irridia commented
Thanks @topherCantrell! This was still on my list, but hadn't yet made it to the top.

2021-01-25 10:01 UTC, johanbrandhorst requested changes
Thanks for this! Could you please add a new test case that exhibits the new behaviour too?

2021-01-26 16:44 UTC, topherCantrell commented
There we go. A test for multiple repeats.

2021-01-28 10:04 UTC, johanbrandhorst approved these changes
Nice, thanks a lot for this!

2021-01-28 10:04 UTC, merged