Add documentation extracting http path from context
grpc-ecosystem/grpc-gateway pull request #2201
Opened 2021-06-23 11:04 UTC by 0daryo

#### References to other Issues or PRs
Add documentation about #2195 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes.
#### Brief description of what is fixed or changed
Adding documentation of PR #2195.
How to define and extract data from annotated context.
#### Other comments
I am not very good at documentation in english 😇 . Let me know any problem.

2021-06-27 22:28 UTC, johanbrandhorst requested changes
Great start, I made some fixes and suggestions!

2021-06-27 22:28 UTC, johanbrandhorst commented on docs/docs/operations/annotated_context.md
> +# AnnotatedContext
```suggestion
# Extracting the HTTP path pattern for a request

It is often interesting to know what [HTTP path pattern](https://github.com/googleapis/googleapis/blob/869d32e2f0af2748ab530646053b23a2b80d9ca5/google/api/http.proto#L61-L87) was matched for a specific request, for example for metrics. This article explains how to extract the HTTP path pattern from the request context.
```

2021-06-27 22:28 UTC, johanbrandhorst commented on docs/docs/operations/annotated_context.md
> +1. Define HTTP path in proto option like below, following template ```google.api.http```.
```suggestion
1. Define the HTTP path in the proto annotation. For example:
```

2021-06-27 22:28 UTC, johanbrandhorst commented on docs/docs/operations/annotated_context.md
> +You can pass data to backend by adding them to metadata or push them to metrics server.
```suggestion
2. At runtime, get the HTTP path pattern from the annotated context, for example using the `WithMetadata` function.
You can pass data to your backend by adding them to the gRPC metadata or push them to a metrics server.
```

2021-06-28 02:09 UTC, 0daryo commented
@johanbrandhorst
Thank you for reviewing so kindly!
I just fixed docs.

2021-06-28 02:42 UTC, johanbrandhorst approved these changes

2021-06-28 02:42 UTC, merged

2021-06-28 02:44 UTC, johanbrandhorst commented
Thanks for your contribution!