fix: Set Content-Type from marshaler on stream error
grpc-ecosystem/grpc-gateway pull request #2313
Opened 2021-08-30 11:21 UTC by vegather

#### References to other Issues or PRs

--

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

The marshaler was used to marshal the body of a stream error, but the content type was not used, leaving it as `text/plain; charset=utf-8`. This uses the content type as defined by the marshaler if the headers have not already been written.

#### Other comments

--

2021-08-30 22:48 UTC, johanbrandhorst requested changes
This looks reasonable to me, but it'd be great to have a test case that was broken before and is fixed by this change, so that we can protect ourselves against losing this again in the future. Could you see if you can add a test to [handler_test.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/f81c435e72054a3fd141c7c9a9d64de291f363de/runtime/handler_test.go#L28)?

2021-08-31 08:40 UTC, vegather commented
Updated the tests to check the `Content-Type` if there is a body. The tests now fail without the fix and pass with the fix.

Good call updating the tests! Turns out I had `w.Header().Set...` and `w.WriteHeader...` in the wrong order.

2021-09-01 01:28 UTC, johanbrandhorst approved these changes
LGTM

2021-09-01 01:28 UTC, merged

2021-09-01 01:28 UTC, johanbrandhorst commented
Thanks for your contribution!