Add docs for merging OpenAPI into a single file
grpc-ecosystem/grpc-gateway pull request #2354
Opened 2021-09-24 18:50 UTC by alee792

Adding a quick section to OpenAPI docs t describe generation into a single, merged file.

I also fixed the hierarchy of the templating section. I also added another "enums_as_ints" section so that "merge" wouldn't get lonely. It serves as a reference for future additions.

No issue, requested in gophers slack:
https://gophers.slack.com/archives/CBATURP1D/p1632504587076100

2021-09-24 18:51 UTC, alee792 commented
@googlebot I signed it!

2021-09-25 01:11 UTC, johanbrandhorst commented
Hi, it looks like the CLA bot is a bit confused about your commit - it needs to be able to link your commit with your github account. Could you try recreating the commit with the same email you use for github?

2021-09-25 01:16 UTC, johanbrandhorst requested changes
Thanks a lot for this!

2021-09-25 01:16 UTC, johanbrandhorst commented on docs/docs/mapping/customizing_openapi_output.md
> +--openapiv2_out . bar=baz,color=red:.
This isn't correct use of protoc, I think you want this
```suggestion
--openapiv2_out . --openapiv2_opt bar=baz,color=red
```

2021-09-25 01:16 UTC, johanbrandhorst commented on docs/docs/mapping/customizing_openapi_output.md
> +Or, with `buf` in `buf.gen.yml`:
Nit: we use `buf.gen.yaml` generally, though we support both.
```suggestion
Or, with `buf` in `buf.gen.yaml`:
```

2021-09-27 14:19 UTC, alee792 commented
@googlebot I consent.

2021-09-27 14:21 UTC, alee792 commented
Alright, I bungled git here. Let's try this again 😅

2021-09-28 01:22 UTC, johanbrandhorst requested changes
Lets just fix the mod file changes, then this looks good to go!

2021-09-28 01:22 UTC, johanbrandhorst commented on go.mod
> +  google.golang.org/grpc v1.41.0
Not sure what happened here, but this is the last thing that needs fixing here.

2021-09-29 03:14 UTC, johanbrandhorst approved these changes

2021-09-29 03:14 UTC, merged

2021-09-29 03:14 UTC, johanbrandhorst commented
Thanks for your contribution 😍