chore(examples): some modifications
grpc-ecosystem/grpc-gateway pull request #2422
Opened 2021-11-15 08:39 UTC by alissa-tung

The current version of `BulkEcho` server is not streaming enough, namely, it can not do `Send` data once `Recv`ed.

2021-11-15 08:41 UTC, alissa-tung commented
@googlebot I signed it!

2021-11-16 02:30 UTC, johanbrandhorst requested changes
I pushed some changes that were causing the tests and generation to fail. Still a bit confused about the rationale for this change. What made you want to change this?

2021-11-16 02:30 UTC, johanbrandhorst commented on examples/internal/server/a_bit_of_everything.go
> -	})
Looks like the new version of this function isn't setting this header.

2021-11-16 02:30 UTC, johanbrandhorst commented on examples/internal/server/a_bit_of_everything.go
> -	}))
Or this trailer.

2021-11-16 02:44 UTC, alissa-tung commented
> I pushed some changes that were causing the tests and generation to fail. Still a bit confused about the rationale for this change. What made you want to change this?

Oh sorry, my original intention is to make the semantic changed first and then fix the metadata if they are not going wrong.
Thanks for working on this. If i am not misunderstanding, the original impl do something like collection all msgs til EOF occur, and range them and send back.

A simple test is like
```sh
#!/usr/bin/sh
for _ in $(seq 10)
do xs="{\"value\": \"$(date +%s)\"}"
   echo "$xs"
   sleep 1
done | cat |
strace -t                                 \
  -e sendto,read -o /tmp/streaming.log    \
    curl --trace-ascii - -k               \
      -X POST                             \
      -H "Content-Type: application/json" \
      -H "Transfer-Encoding: chunked"     \
      -T -                                \
        'http://127.0.0.1:6580/echo'
```

which got the result like

```
==>
==>
==>
==>
... ...
<==
<==
<==
<==
```

instead of return immediately

```
==>
<==
==>
<==
... ...
==>
<==
```

I am not sure about which is the properly streaming model it would be demonstrate there.

2021-11-16 02:48 UTC, alissa-tung commented
Seems that grpc-go put the recv-send procedure in one for too
https://github.com/grpc/grpc-go/blob/b2317c762757d277fea21e68c714c6b423675570/examples/features/cancellation/server/main.go#L40

2021-11-17 01:18 UTC, johanbrandhorst commented
I don't think we need to change this. It's being used in some tests. It's not really supposed to show off anything. I'm leaning towards rejecting this PR if there isn't a bug here.

2021-11-17 02:09 UTC, alissa-tung commented
Okay, thx.

2021-11-17 02:09 UTC, closed without merging