Fixes #407 and $1700 - RFC 6570 path parameter constraints and multiple HTTP path/method endpoint support
grpc-ecosystem/grpc-gateway pull request #2461
Opened 2021-12-09 02:07 UTC by betmix-matt

#### References to other Issues or PRs
Fixes $407
Fixes #1700

#### Brief description of what is fixed or changed
This PR changes the behavior of the protoc-gen-openapiv2 plugin when multiple gRPC operations match the same HTTP path and method and include a path parameter.  Previously, all path parameters were converted from their RFC 6570 syntax to OpenAPI syntax (i.e. `/v1/{bar=foos/*}` to `/v1/{bar}`) unless the parameter was named `name` or `parent`.  This caused invalid OpenAPI specifications when `name` or `parent` path params existed with constraints.

With this PR, when a given gRPC service method has an identical OpenAPI HTTP endpoint to another service, the plugin will now rename the path parameter on the 2nd service adding a _1 suffix (or _2 etc until it doesn't match an existing endpoint).   This will not change the actual contents of requests being sent to the endpoint as path parameter names are replaced with the values when making a request.

This PR also adds automatic "pattern" generation on path parameters that use the RFC 6570 path parameter constraints like `/v1/{name=foos/*}/bar` so that the OpenAPI specification properly matches the proto definition's requirements

Tests added for all changes.

2021-12-09 02:20 UTC, johanbrandhorst commented
Thanks for your contribution! I will review this in a bit, but note that you'll probably need to sign the Google CLA if you haven't already (see https://github.com/grpc-ecosystem/grpc-gateway/pull/2307#issuecomment-906183149 for instructions - not sure why the bot isn't replying to the PR directly anymore). It may be that you need to sign it and the bot still doesn't reply, in that case can you please share a screenshot of your registered signing of the CLA from the CLA website? I will get to looking into this soon!

2021-12-09 04:38 UTC, betmix-matt commented
All set now.

2021-12-09 04:44 UTC, betmix-matt commented
<img width="978" alt="Screen Shot 2021-12-08 at 8 42 27 PM" src="https://user-images.githubusercontent.com/92820658/145335926-2c5f4615-49b0-43a7-b7da-9e36b9de2cf9.png">

2021-12-10 19:40 UTC, betmix-matt commented
I wanted to note I have used the updated version in my company's repository and it is now able to properly route the RFC 6570 format and enforced that the path parameter on the swagger page matched the given pattern.

2021-12-12 02:48 UTC, johanbrandhorst requested changes
This is a really amazing contribution, thank you so much! I would ideally like to preserve the existing behavior here and add a warning log in the case of two matching routes.

I would like to see us remove the `assert` test function that was added as it's very at odds with the existing conventions of the test code, even if that makes the test verbose.

I'm also a little worried about the mux change. Could you please explain what the change is for?

2021-12-12 02:48 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template_test.go
> +func assertEqual(t *testing.T, testName string, a interface{}, b interface{}) {
I appreciate the intention here, but this pattern is inconsistent with the rest of the code, and I don't think we should introduce it here. If you want to do this, we'll need one function for each type you want to test:
```go
func assertEqualInt(t *testing.T, testName string, a int, b int) {
```

2021-12-12 02:48 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template_test.go
> +	assertEqual(t, "Results paths length", len(result.Paths), 4)
I would sooner just make this explicit than use assertion functions
```suggestion
	if got, want := len(result.Paths), 4; got != want {
		t.Fatalf("Results paths length differed, got %d want %d", got, want)
	}
```

2021-12-12 02:48 UTC, johanbrandhorst commented on runtime/mux.go
> +	EncodedPathSplitter = regexp.MustCompile("(/|%2F)")
Does this need to be exported?

2021-12-12 02:48 UTC, johanbrandhorst commented on runtime/mux.go
> +	}
What, if any, are the routing consequences of this change? Is this a change in behavior?

2021-12-12 02:48 UTC, johanbrandhorst commented on runtime/mux_test.go
> +						_, _ = fmt.Fprintf(w, "%s %s", p.method, pat.String())
Thanks for tidying up ❤️

2021-12-14 06:18 UTC, betmix-matt commented
We should be all set now! All requested changes have been incorporated.

2021-12-15 01:48 UTC, johanbrandhorst approved these changes
This is hands down one of the best contributions I've ever reviewed - very thoughtfully researched, implemented and documented. On behalf of the maintainers and the community - thank you!

2021-12-15 01:48 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template_test.go
> +	os.Stderr = w
This is one of the craziest things I've seen but I think I will allow it 😅.

2021-12-15 01:48 UTC, johanbrandhorst commented on runtime/mux.go
>  	UnescapingModeAllCharacters
👏🏻 thank you for this

2021-12-15 02:02 UTC, merged

2021-12-15 04:17 UTC, betmix-matt commented
Thank you for putting your time into making this project function!

Users of `grpc-gateway` can now use the Google style API syntax for the gRPC endpoints and still have a RESTful JSON HTTP 1.0 API with a valid OpenAPI specification!

Could I possibly ask for a release?  I want to use this immediately in our organization and I can't merge if it isn't a public version :-)

2021-12-15 14:36 UTC, johanbrandhorst commented
I'll make a patch release this evening, as this should probably just be considered a bug fix.

2021-12-16 01:11 UTC, johanbrandhorst commented
v2.7.2 is out!

2021-12-31 02:06 UTC, dgparker commented
This is huge! thank you so much @betmix-matt

2022-01-10 16:27 UTC, johanbrandhorst commented
It appears this may have introduced a regression: https://github.com/grpc-ecosystem/grpc-gateway/issues/2489. We should be able to add a test case mimicking the behaviour reported to help track down the issue.