correct generate field mask for google.protobuf.struct field
grpc-ecosystem/grpc-gateway pull request #2619
Opened 2022-03-30 07:52 UTC by marsianin

#### References to other Issues or PRs

This is suggestion to fix https://github.com/grpc-ecosystem/grpc-gateway/issues/2618 (if it is the issue)

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

Yes
#### Brief description of what is fixed or changed

Correct default field mask generation for google.protobuf.struct

#### Other comments

2022-04-01 22:19 UTC, johanbrandhorst requested changes
Please add a test that reproduces the issue and is fixed by this PR. I think this fix looks good, but it would be nice to have a review from @talanknight who contributed this originally too.

2022-04-03 11:55 UTC, marsianin commented
Hello @johanbrandhorst 
Added one more test for the issue.

Behaviour for **PASSED** case for the test before PR changes
```
	input:    `{"lineNum": 123, "structField": {"name":"bob"}}`,
	expected: newFieldMask("line_num", "structField.name"),
```

Behaviour for **PASSED** case for the test now
```
	input:    `{"lineNum": 123, "structField": {"name":"bob"}}`,
	expected: newFieldMask("line_num", "struct_field.name"),
```

2022-04-03 17:05 UTC, johanbrandhorst approved these changes

2022-04-03 18:04 UTC, merged

2022-04-03 18:04 UTC, johanbrandhorst commented
Thanks for your contribution!