support google.protobuf.Value
grpc-ecosystem/grpc-gateway pull request #2628
Opened 2022-04-06 12:49 UTC by wclssdn

#### References to other Issues or PRs

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

yes

#### Brief description of what is fixed or changed

Support `google.protobuf.Value` type in proto files, when request with x-www-form-urlencoded.

#### Other comments

2022-04-07 01:17 UTC, johanbrandhorst requested changes
Please add a few new testcases to test the marshaling behavior. Should we add `google.protobuf.Struct` support at the same time?

2022-04-07 01:17 UTC, johanbrandhorst commented on runtime/query.go
> +		msg = v
I think we should use `protojson`, not the standard library marshaler. Also, can't we just do this in one fell swoop?
```suggestion
		var v structpb.Value
		err := protojson.Unmarshal([]byte(value), &v)
		if err != nil {
			return protoreflect.Value{}, err
		}
		msg = &v
```

2022-04-07 02:01 UTC, wclssdn commented
> Please add a few new testcases to test the marshaling behavior. Should we add `google.protobuf.Struct` support at the same time?

OK, i'm trying to do that.

2022-04-07 06:19 UTC, wclssdn commented
> Please add a few new testcases to test the marshaling behavior. Should we add `google.protobuf.Struct` support at the same time?

I have added some testcases to test `google.protobuf.Struct` and `google.protobuf.Value` support.

2022-04-08 02:03 UTC, wclssdn commented
> 

It's very common in different projects. Especially in PHP projects. If I rewrite PHP project to Go, I must implement the origin logic.

Even a Go project, that also need a unknown json object to deal with. e.g. `payload` field, it provide a method for client to save there personal data.

2022-04-08 14:15 UTC, johanbrandhorst commented
Please rebase on master for latest linter

2022-04-09 03:59 UTC, wclssdn commented
> Please rebase on master for latest linter

done~

2022-04-10 02:44 UTC, johanbrandhorst approved these changes

2022-04-10 02:45 UTC, merged

2022-04-10 02:45 UTC, johanbrandhorst commented
Thanks for your contribution!