protoc-gen-openapiv2: Fully support all HTTP methods in OpenAPI
grpc-ecosystem/grpc-gateway pull request #2726
Opened 2022-05-29 19:28 UTC by mnito

#### References to other Issues or PRs

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yep

#### Brief description of what is fixed or changed

The handling for mappings with the same path and method caused a crash when provided with an operation with a HEAD, OPTIONS, or TRACE HTTP method, which are all technically supported by OpenAPI.

Also fix this same crash when an unsupported HTTP method is provided

#### Other comments

I didn't dig into the "why" of the existing pattern too much -- I wonder if it's possible to simplify in a follow-up change to not require the explicit HTTP method switch statements etc?

2022-05-29 19:50 UTC, johanbrandhorst requested changes
Hi, thanks for this fix. I guess no one ever tried using these verbs 😂. Do you mind adding some example methods with these verbs as mappings to our examples? See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto

2022-05-29 19:57 UTC, mnito commented
> Hi, thanks for this fix. I guess no one ever tried using these verbs 😂. Do you mind adding some example methods with these verbs as mappings to our examples? See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto

Ha yeah I got a little cute some years back and used HEAD for an exists method in a service and it crashed when upgrading gRPC gateway 😭 . Yeh I can do that.

2022-05-29 23:21 UTC, mnito commented
Should be good to go now, let me know what you think

2022-05-30 15:46 UTC, johanbrandhorst approved these changes
This is a quality PR, thanks for adding the integration tests!

2022-05-30 15:46 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/types.go
> +	// Trace   *openapiOperationObject `json:"trace,omitempty" yaml:"trace,omitempty"`
_nice_

2022-05-30 15:46 UTC, merged

2022-05-30 23:44 UTC, mnito commented
Thanks!