Make read_only work with references using AllOf
grpc-ecosystem/grpc-gateway pull request #3082
Opened 2022-12-20 18:57 UTC by same-id

#### References to other Issues or PRs

Fixes #1137

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

As described here:

https://github.com/grpc-ecosystem/grpc-gateway/issues/1137

This partially reverts the recent commit:

a0fe8d7c8676db9674ccbc4c4fc642790a8b8065

Which doesn't solve the problem for read_only being set on the field.

This feature will require setting the "use_allof_for_refs" to true since this breaks existing compatibility with swagger-codegen generated files from the AllOf'd schema - type is now "object" and not $ref.

Test added + ReDoc now works with read_only message/enum fields.

#### Other comments

2022-12-21 03:40 UTC, johanbrandhorst commented
Please rebase on `main`, I've fixed the Bazel error

2022-12-21 05:24 UTC, johanbrandhorst reviewed
Hi, I'm a little confused about this, but before diving into the fix itself, I'm wondering if your need for read only fields can be satisfied by using the OUTPUT_ONLY field annotation? See https://github.com/grpc-ecosystem/grpc-gateway/blob/492703c51e9c90b84e404ff11562407573e405fb/examples/internal/proto/examplepb/a_bit_of_everything.proto#L386 for an example. We might be better off just removing this annotation from here and only supporting this other field annotation.

2022-12-21 06:45 UTC, same-id commented
> Please rebase on `main`, I've fixed the Bazel error

Done

> Hi, I'm a little confused about this, but before diving into the fix itself, I'm wondering if your need for read only fields can be satisfied by using the OUTPUT_ONLY field annotation? See
> 
> https://github.com/grpc-ecosystem/grpc-gateway/blob/492703c51e9c90b84e404ff11562407573e405fb/examples/internal/proto/examplepb/a_bit_of_everything.proto#L386
> 
> for an example. We might be better off just removing this annotation from here and only supporting this other field annotation.

Not sure I follow - this is exactly OUTPUT_ONLY.
This commit is about making OUTPUT_ONLY generate the correct Redoc documentation.

`OUTPUT_ONLY` is the protobuf annotation, `readOnly` is the OpenAPI parameter.

If I specify OUTPUT_ONLY on Enums/Sub-messages - this doesn't work in OpenAPI v2 since Enums/Sub-messages are translated to $ref, and according to OpenAPI v2 you can't have readOnly in the same level - so when I later use Redoc on the output of the swagger.yaml file, `readOnly` is not set correctly and ReDoc ignores it, resulting in a non readonly field in the documentation.

Here is another illustration of the problem and the solution.

https://stackoverflow.com/a/51402417

2022-12-21 16:27 UTC, johanbrandhorst commented
I see, apologies for the confusion. The issue you linked describes using the `read_only` field annotation, which is different from the OUTPUT_ONLY field annotation:

```protobuf
string id = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {read_only: true}];
```.

2022-12-21 16:30 UTC, johanbrandhorst requested changes
This change looks simple enough, but it looks like it's missing the bazel changes required for new flags, please have a look at https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/defs.bzl#L352 for an example.

2022-12-21 17:35 UTC, same-id commented
> I see, apologies for the confusion. The issue you linked describes using the `read_only` field annotation, which is different from the OUTPUT_ONLY field annotation:
> 
> ```proto
> string id = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {read_only: true}];
> ```

Ah, I see the confusion now.
However this change will work for both, OUTPUT_ONLY and read_only swagger proto annotation since I'm doing the change at a point where the logic is unified

2022-12-21 17:35 UTC, same-id commented
> This change looks simple enough, but it looks like it's missing the bazel changes required for new flags, please have a look at https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/defs.bzl#L352 for an example.

Will do

2022-12-21 17:41 UTC, same-id commented
Done

2022-12-21 18:02 UTC, johanbrandhorst approved these changes
LGTM

2022-12-21 18:03 UTC, merged

2022-12-21 18:03 UTC, johanbrandhorst commented
Thanks for your contribution!

2022-12-22 10:19 UTC, warrenb95 commented
Hi I've been following on with this MR and I was just wondering why `use_allof_for_refs` hasn't been added in these other places like what was done with `visibility_restriction_selector`:
* https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/defs.bzl#L206
* https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/defs.bzl#L130

---
I've tried using `use_allof_for_refs` but getting an error `no such flag` with version v2.15.0

2022-12-22 17:34 UTC, johanbrandhorst commented
Argh, I guess we missed some of the places when adding this option, @same-id would you mind tidying this up?

2022-12-25 10:56 UTC, sam-utila commented
Missed it, thanks for fixing :-)