Add `format` in path params
grpc-ecosystem/grpc-gateway pull request #3089
Opened 2022-12-22 18:02 UTC by antgamdia

#### References to other Issues or PRs

Fixes #3070

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yep!

#### Brief description of what is fixed or changed

This PR is adding the `format` field in the OpenAPI generator, which was wrongly set to `""` in some cases.

#### Other comments

I haven't been able to add a test case for the actual failing scenario (a path param with a `format` in the field options). However, I have added some test cases covering the "string with format" scenario in other params (headers and query).
If you can point me to the proper test function, I'll happily add a test case.

2022-12-22 19:43 UTC, johanbrandhorst requested changes
This looks like a great start, thank you!

2022-12-22 19:43 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +		// NOTE: in OpenAPI specification, can be empty on string type
While we're here, can we add a reference to the data types part of the spec to the docstring of this function? This link: https://swagger.io/specification/v2/#data-types.

2022-12-22 19:43 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +							paramFormat = schema.Format
Please add a comment here to describe why this is happening
```suggestion
							// If the is no mandatory format based on the field,
							// allow it to be overridden by the user.
							paramFormat = schema.Format
```

2022-12-22 23:30 UTC, antgamdia commented
> This looks like a great start, thank you!

Thank you! I've added the current suggestions you made, however, I have to wait a few days (perhaps more in these Christmas days?) til I get the OK for signing the CLA in my company. As soon as I have it, I'll sign it straight away :)

2023-01-09 09:54 UTC, antgamdia commented
> however, I have to wait a few days (perhaps more in these Christmas days?) til I get the OK for signing the CLA in my company. As soon as I have it, I'll sign it straight away :)

Done :)

2023-01-09 17:52 UTC, johanbrandhorst approved these changes

2023-01-09 18:02 UTC, johanbrandhorst commented
Looks like some files need to be regenerated after this change, see CONTRIBUTING.md. Thanks!

2023-01-10 14:17 UTC, antgamdia commented
> Looks like some files need to be regenerated after this change, see CONTRIBUTING.md. Thanks!

Yep, sorry, you're right, I missed an autogenerated file :sweat_smile: Adding it now!

2023-01-12 04:07 UTC, merged

2023-01-12 04:08 UTC, johanbrandhorst commented
Thanks for your contribution!