Support field extensions with use_allof_for_refs
grpc-ecosystem/grpc-gateway pull request #3100
Opened 2022-12-27 18:45 UTC by same-id

#### References to other Issues or PRs

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

Allow extensions to be used with the recently added AllOf feature

#### Other comments

2022-12-28 04:26 UTC, johanbrandhorst requested changes
Hi, thank you for this, I think it's probably a good time to add an example protobuf file that is generated with this option turned on, so we can see the difference introduced by this sort of chance. Please add a small new file to the https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples/internal/proto/examplepb folder. You'll need a new `buf.gen.yaml` file which sets this option, see the existing files in the directory for an example. Thanks!

2022-12-28 21:22 UTC, same-id commented
Will do.

2023-06-18 12:02 UTC, same-id commented
Hey, still haven't got to creating a whole new example protobuf.

I see that some other PRs extending my work have also made their way there:

https://github.com/grpc-ecosystem/grpc-gateway/pull/3240

2026-06-10 18:41 UTC, same-id commented
Hi, @johanbrandhorst 

Been some time

Wanted to try and upstream one of our private changes, tended to your requested changes.

Not sure if I should also look at the v3 tree.

2026-06-15 04:39 UTC, johanbrandhorst approved these changes
Thanks!

2026-06-15 04:39 UTC, merged