Update README to use new remote plugins
grpc-ecosystem/grpc-gateway pull request #3132
Opened 2023-01-17 23:19 UTC by pkwarren

#### Brief description of what is fixed or changed

Update the example buf.gen.yaml in the README to use the new remote plugins.

2023-01-17 23:23 UTC, johanbrandhorst requested changes
This is great, do you mind updating our own `buf.gen.yaml` too? https://github.com/grpc-ecosystem/grpc-gateway/blob/main/buf.gen.yaml

2023-01-17 23:47 UTC, pkwarren commented on Makefile
> +	go install github.com/bufbuild/buf/cmd/buf@v1.12.0
New `plugin:` key in buf.gen.yaml requires Buf CLI 1.8+: https://docs.buf.build/bsr/remote-plugins/migrating-from-alpha#bufgenyaml-changes.

2023-01-17 23:52 UTC, johanbrandhorst approved these changes

2023-02-11 04:19 UTC, johanbrandhorst commented
Looks like the buf update changed the formatting, do you mind taking another look?

2023-02-28 06:15 UTC, johanbrandhorst commented
I think this was superceded

2023-02-28 06:15 UTC, closed without merging