use_allof_for_refs: extend to example field
grpc-ecosystem/grpc-gateway pull request #3240
Opened 2023-03-13 17:07 UTC by igor-tsiglyar

#### References to other Issues or PRs

Related to https://github.com/grpc-ecosystem/grpc-gateway/issues/3232, https://github.com/grpc-ecosystem/grpc-gateway/issues/2671

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

Extending https://github.com/grpc-ecosystem/grpc-gateway/pull/3082, we can enable setting enum field example in `openapiv2_field` annotation, e.g.

```
  // Severity of this alert
  AlertSeverity severity = 5 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      example: "\"CRITICAL\""
    }
  ];
```
produces
```
        "severity": {
          "example": "CRITICAL",
          "title": "Severity of this alert",
          "allOf": [
            {
              "$ref": "#/definitions/AlertSeverity"
            }
          ]
        },
```
instead of `example` field being ignored, which is currently the case.

2023-03-14 03:50 UTC, johanbrandhorst requested changes
This seems reasonable, but I think we should add at least one test. Either add a new test case in `template_test.go` (there's hopefully already one for the allOf option) or add a new protobuf file and generate from it with this option enabled please.

2023-03-14 11:43 UTC, igor-tsiglyar commented
@johanbrandhorst I have extended the existing relevant test to verify the example property being included, as well as others from the include condition (title, description) https://github.com/grpc-ecosystem/grpc-gateway/pull/3240/files#diff-0330d83e3109c5c0a8cb78a2a980db731e973c738da7851d34a88e00244a4b5eR5375

2023-03-15 04:23 UTC, johanbrandhorst approved these changes
LGTM

2023-03-15 04:34 UTC, merged

2023-03-15 04:34 UTC, johanbrandhorst commented
Thanks for your contribution!

2023-03-15 10:20 UTC, igor-tsiglyar commented
@johanbrandhorst Sure, thanks for driving this project