feat(#3238):Support map in query parameters
grpc-ecosystem/grpc-gateway pull request #3323
Opened 2023-05-25 09:07 UTC by li31727

#### References to other Issues or PRs

Fixes #3238 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
Generate the swagger api for Get requests that pass map type parameters
#### Other comments

2023-05-29 17:47 UTC, johanbrandhorst requested changes
Thanks a lot for this!

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +						// this will generate a query name is  map_name[key_type]
```suggestion
						// This will generate a query in the format map_name[key_type]
```

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +						schema.Description = `This is a request variable of the map type. The query form is map_name[key]= value,e. g: If the map name is Age, the key type is string, and the value type is integer, the
```suggestion
						schema.Description = `This is a request variable of the map type. The query format is "map_name[key]=value", e.g. If the map name is Age, the key type is string, and the value type is integer, the query parameter is expressed as Age["bob"]=18`
```

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +					}
Can you invert this and return early instead?
```go
kType, err := getMapParamKey(k.GetType())
if err != nil {
    return nil, err
}
```

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +
Remove this line please

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +
Remove this line please

2023-05-29 17:47 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template.go
> +	}
Please invert this
```suggestion
	if !ok || f == "byte" || f == "float" || f == "double" {
		return "", fmt.Errorf("unsupported type: %q", f)
	}
	return tType, nil
```

2023-05-29 17:48 UTC, li31727 commented
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2023-05-31 03:45 UTC, li31727 commented
CI/golangci   It's strange that I can run success on my reposity but not here，Please try golangci again

2023-05-31 03:46 UTC, li31727 commented
CI/golangci   It's strange that I can run success on my reposity but not here，Please try golangci again

2023-05-31 04:14 UTC, johanbrandhorst requested changes
Thanks for the updates, I missed one case of an extra newline, but I also wanted to ask if you could try using one of these object parameters in one of our Go integration tests: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/integration/integration_test.go. Maybe have a look and see if it makes sense anywhere, if not, that's okay.

2023-05-31 04:14 UTC, johanbrandhorst commented on protoc-gen-openapiv2/internal/genopenapi/template_test.go
> +
Please remove this newline

2023-05-31 06:42 UTC, li31727 commented
>

2023-05-31 06:50 UTC, li31727 commented
> https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/integration/integration_test.go

I in https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/integration/integration_test.go has added a map types of G ET request parameter, I don't know whether there is a problem in my test code, I found that grpc-gateway does not seem to support GET requests with a value of type message

2023-05-31 15:09 UTC, johanbrandhorst commented
Seems like the tests are passing, so I think that test is great, thank you!

2023-05-31 15:09 UTC, johanbrandhorst approved these changes

2023-05-31 15:09 UTC, merged

2023-05-31 15:09 UTC, johanbrandhorst commented
Thank you for your contribution!