Omit enum field when value is empty
grpc-ecosystem/grpc-gateway pull request #4180
Opened 2024-04-07 23:06 UTC by jeromefroe

#### References to other Issues or PRs

Fixes #4179.

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes.

#### Brief description of what is fixed or changed

This commit fixes by #4179 by updating the `listEnumNumbers` and `listEnumNames` functions to return a nil interface when the set of enums is empty. The functions currently returned typed slices but when the `Enum` field in the `openapiParameterObject` type is set to the returned value, the values [aren't considered nil even when the slices are empty because the interfaces contain a type value](https://go.dev/doc/faq#nil_error). And the `omitempty` option for the field therefore won't omit the field as a result.

#### Other comments

2024-04-08 20:03 UTC, johanbrandhorst requested changes
This is a great fix, do you think you could write a test that exhibits the behavior? We have some integration tests in `examples/internal/integration`.

2024-04-09 00:22 UTC, jeromefroe commented on examples/internal/proto/examplepb/enum_with_single_value.swagger.json
> +    "examplepbEnumWithSingleValue": {
With this change, we can see that the `enum` field is now omitted from the Swagger spec for this enum that has just a single value.

2024-04-09 16:18 UTC, johanbrandhorst approved these changes
Thanks!

2024-04-10 18:59 UTC, johanbrandhorst commented
Looks like there are still some lint errors 😬

2024-04-11 16:50 UTC, johanbrandhorst commented
😬

2024-04-11 21:42 UTC, merged

2024-04-11 22:00 UTC, johanbrandhorst commented
Thank you!