Add support for method's deprecated option
grpc-ecosystem/grpc-gateway pull request #4373
Opened 2024-05-26 11:37 UTC by vajexal

https://github.com/grpc-ecosystem/grpc-gateway/issues/2906
https://github.com/grpc-ecosystem/grpc-gateway/pull/2872

this pr adds support for `option deprecated = true;` in method description, e. g.

```
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option deprecated = true;
  }
}
```

instead of

```
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      deprecated: true
    }
  }
}
```

some breaking change: we will mark method deprecated if any option says so, thus if method's deprecated option is true and openapiv2_operation's deprecated is false, openapiv2 method would be deprecated (before this pr method wouldn't be deprecated). This will happen because we can't differ openapiv2_operation's deprecated = false from absence of the field, so we process openapiv2_operation's deprecated field only if it's true

2024-05-28 04:04 UTC, johanbrandhorst requested changes
Thank you for this thoughtful PR! I especially appreciate that you outlined the breaking changes involved. I think, because this introduces behavior that can't be turned off, we need to only enable this behavior under a flag. If it was possible to have the OpenAPIv2 annotation override the protobuf annotation I think it'd be fine to have this enabled by default, but as it is I think we need an option. How about `enable_rpc_deprecation`?

2024-05-30 22:06 UTC, johanbrandhorst requested changes
Could you please add a bazel flag for the new option too?

2024-05-30 22:06 UTC, johanbrandhorst commented on internal/descriptor/registry.go
> +	// enableRpcDeprecation whether to process grpc method'd deprecated option
```suggestion
	// enableRpcDeprecation whether to process grpc method's deprecated option
```

2024-05-30 22:06 UTC, johanbrandhorst commented on protoc-gen-openapiv2/main.go
> +	enableRpcDeprecation           = flag.Bool("enable_rpc_deprecation", false, "whether to process grpc method'd deprecated option.")
```suggestion
	enableRpcDeprecation           = flag.Bool("enable_rpc_deprecation", false, "whether to process grpc method's deprecated option.")
```

2024-05-31 17:01 UTC, vajexal commented
i'm not good at bazel, so correct me if i'm wrong somewhere

2024-05-31 17:03 UTC, vajexal commented
and should this option be added to `docs/docs/mapping/customizing_openapi_output.md`?

2024-05-31 17:18 UTC, johanbrandhorst commented
> and should this option be added to `docs/docs/mapping/customizing_openapi_output.md`?

Sure, that'd be great!

2024-05-31 17:18 UTC, johanbrandhorst commented
> i'm not good at bazel, so correct me if i'm wrong somewhere

This looks fine, thank you.

2024-06-02 04:07 UTC, johanbrandhorst approved these changes
Looks great!

2024-06-02 04:17 UTC, merged