docs: add example to fully override http responses
grpc-ecosystem/grpc-gateway pull request #4564
Opened 2024-07-27 10:44 UTC by nguyentranbao-ct

Updates the documentation to include an example of fully overriding custom HTTP responses using a Forward Response Option and a Custom Marshaller.

#### References to other Issues or PRs

Not actually a fix, but a guide that partially supports #4483 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

- Provided an example with CreateUserResponse proto message.
- Demonstrated setting up gRPC-Gateway with custom options.
- Included a forwardResponse function and a custom marshaller ResponseWrapper.

2024-07-28 01:04 UTC, johanbrandhorst requested changes
Thanks for this, just a few comments!

2024-07-28 01:04 UTC, johanbrandhorst commented on docs/docs/mapping/customizing_your_gateway.md
> +Create a custom marshaller to format the response data which utilizes the builtin JSON marshaller:
```suggestion
Create a custom marshaler to format the response data which utilizes the builtin JSON marshaler as a fallback:
```

2024-07-28 01:04 UTC, johanbrandhorst commented on docs/docs/mapping/customizing_your_gateway.md
> +  return json.Marshal(resp)
I think you may want to use `c.JSONPb.Marshal`? It's important to use a protobuf-aware JSON marshaler with protobuf types.
```suggestion
  return c.JSONPb.Marshal(resp)
```

2024-07-28 01:04 UTC, johanbrandhorst commented on docs/docs/mapping/customizing_your_gateway.md
> +  runtime.JSONBuiltin
I think this should embed `runtime.JSONPb` to make sure it supports protobuf messages in general (the behavior will differ around things like enums, oneofs, etc). See https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime#JSONPb.

2024-07-29 04:15 UTC, nguyentranbao-ct commented
I’d like to add our company to the adopters list too, if that’s alright.

2024-07-30 20:40 UTC, johanbrandhorst approved these changes
Awesome, thanks!

2024-07-30 20:48 UTC, merged